[package]
name = "app_state"
version = "0.1.0"
edition = "2021"

[dependencies]
sequencer = { path = "../sequencer" }
project = { path = "../project" }
audio = { path = "../audio" }
core = { path = "../core" }
log = "0.4"
